# Site settings
# You MUST have a space after the : on each line!!!!
markdown: redcarpet
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/statistical-thinking" # the subpath of your site, e.g. /blog/
url: "http://tstudent.org" # the base hostname & protocol for your site
permalink: pretty
github_username: t-student
sass: 
sass_dir: _sass

# Build settings
#markdown: kramdown
